///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace github_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
          /// <summary>
          ///The Recording1 recording.
          /// </summary>
          [TestModule("152c2345-a1f9-49f1-8b96-3df2ed8e39fb", ModuleType.Recording, 1)]
          public partial class Recording1 : ITestModule
          {
                    /// <summary>
                    /// Holds an instance of the github_testRepository repository.
                    /// </summary>
                    public static github_testRepository repo = github_testRepository.Instance;

                    static Recording1 instance = new Recording1();

                    /// <summary>
                    /// Constructs a new instance.
                    /// </summary>
                    public Recording1()
                    {
                    }

                    /// <summary>
                    /// Gets a static instance of this recording.
                    /// </summary>
                    public static Recording1 Instance
                    {
                              get { return instance; }
                    }

#region Variables

#endregion

                    /// <summary>
                    /// Starts the replay of the static recording <see cref="Instance"/>.
                    /// </summary>
                    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
                    public static void Start()
                    {
                              TestModuleRunner.Run(Instance);
                    }

                    /// <summary>
                    /// Performs the playback of actions in this recording.
                    /// </summary>
                    /// <remarks>You should not call this method directly, instead pass the module
                    /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
                    /// that will in turn invoke this method.</remarks>
                    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
                    void ITestModule.Run()
                    {
                              Mouse.DefaultMoveTime = 300;
                              Keyboard.DefaultKeyPressTime = 20;
                              Delay.SpeedFactor = 1.00;

                              Init();

                              Report.Log(ReportLevel.Info, "User", "testabc123", new RecordItemIndex(0));
                              
                    }

#region Image Feature Data
#endregion
          }
#pragma warning restore 0436
}
